---
title: "Stats Homework 4"
author: "2015-26042 Hyunghun Cho"
date: "Tuesday, October 04, 2016"
output: pdf_document
---

# 5.6 Exercises

## 5.5


## 5.6

## 5.7

## 5.11

## 5.17

## 5.18

## 5.20

## 5.22

## 5.32

## 5.34


# music


```{r}
filename <- 'music.csv'
music <- read.csv(filename, header=TRUE, sep=",")
group.a <- subset(music, Group == 'A')
group.b <- subset(music, Group == 'B')
X.a <- group.a$Completed
X.b <- group.b$Completed
N.a <- length(X.a)
N.b <- length(X.b)
M.a <- mean(group.a$Completed)
M.b <- mean(group.b$Completed)
SS.a <- sum( (X.a - M.a)^2)
SS.b <- sum( (X.b - M.b)^2)
diff.mean <- M.a-M.b
#mu.m <- mu.source
#mu.mm <- mu.source.a - mu.source.b

# by null hypothesis, mu.source.a and mu.source.b is identical
mu.mm <- 0
#sigma.mm <- sqrt(sigma.source^2 / N.a + sigma.source^2 / N.b)
# z <- (M.x.a - M.x.b) / sigma.mm
df <- (N.a - 1) + (N.b - 1)

var.source <- (SS.a + SS.b) / ((N.a - 1) + (N.b - 1))
est_sigma.mm <- sqrt(var.source/N.a + var.source/N.b)
t <- (M.a - M.b) / est_sigma.mm
print (t)
# 95% confindence interval if 
qt(c(.05, .95), df=df)


# 95% confidence interval if H0 is that mu.source.b is either greater or lesser than mu.source.a
qt(c(.025, .975), df=df)

var.test(X.a, X.b)
```

# smoker

```{r, echo=FALSE}
nonsmokers <- c(18, 22, 21, 17, 20, 17, 23, 20, 22, 21)
smokers <- c(16, 20, 14, 21, 20, 18, 13, 15, 17, 21)

plot(density(nonsmokers))
plot(density(smokers))
boxplot(nonsmokers,smokers, names=c("nonsmokers","smokers"))

t.test(nonsmokers, smokers, var.equal = TRUE)
```

# shoe

```{r}
filename <- 'shoes.csv'
shoes <- read.csv(filename, header=TRUE, sep=",")
shoes.diff <- shoes$shoesOn - shoes$shoesOff
N.diff <- length(shoes.diff)
M.diff <- mean(shoes.diff)
SS.diff <- sum( (shoes.diff - M.diff)^2)
var.source <- (SS.diff) / (N.diff - 1)
est_sigma.mm <- sqrt(var.source/N.diff)
t <- (M.diff - 0) / est_sigma.mm
t.test(shoes.diff, mu=0)
```
